SELECT SUM(SCORE) AS SCORE, B.EMP_NO, B.EMP_NAME, B.POSITION,B.EMAIL
FROM HR_DEPARTMENT AS A
INNER JOIN HR_EMPLOYEES AS B
ON A.DEPT_ID = B.DEPT_ID
INNER JOIN HR_GRADE C
ON B.EMP_NO = C.EMP_NO
WHERE C.YEAR = 2022
GROUP BY C.EMP_NO
ORDER BY SCORE DESC
LIMIT 1